//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.VerifyLogs = new HashSet<VerifyLog>();
        }
    
        public int ID { get; set; }
        public string Weixin { get; set; }
        public string PrevWeixin { get; set; }
        public string AgentName { get; set; }
        public int AgentLevel { get; set; }
        public string IDCard { get; set; }
        public string Tell { get; set; }
        public string Address { get; set; }
        public string Emaill { get; set; }
        public string AuthorizeBookNo { get; set; }
        public Nullable<System.DateTime> AuthorizeBooStartDate { get; set; }
        public Nullable<System.DateTime> AuthorizeBooEndDate { get; set; }
        public string ProductName { get; set; }
        public int State { get; set; }
        public string ShopLink1 { get; set; }
        public string ShopAccount1 { get; set; }
        public string ShopLink2 { get; set; }
        public string ShopAccount2 { get; set; }
        public string ShopLink3 { get; set; }
        public string ShopAccount3 { get; set; }
        public string Bussiness { get; set; }
        public int RequestType { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<VerifyLog> VerifyLogs { get; set; }
    }
}
